const kiado=[
{"kod":"1","nev":"Panoráma Kiadó","szekhely":"Budapest"},
{"kod":"2","nev":"Lapkiadó Vállalat","szekhely":"Budapest"},
{"kod":"3","nev":"Statisztikai Kiadó Vállalat","szekhely":"Budapest"},
{"kod":"4","nev":"Helikon Kiadó","szekhely":"Budapest"},
{"kod":"5","nev":"Magvető Kiadó","szekhely":"Budapest"},
{"kod":"6","nev":"Szépirodalmi Könyvkiadó","szekhely":"Budapest"},
{"kod":"7","nev":"Móra Kiadó","szekhely":"Budapest"},
{"kod":"8","nev":"Fekete Sas Kiadó","szekhely":"Budapest"},
{"kod":"9","nev":"Editorg Kiadó","szekhely":"Budapest"},
{"kod":"10","nev":"Akadémiai Kiadó","szekhely":"Budapest"},
{"kod":"11","nev":"Unikornis Kiadó","szekhely":"Budapest"},
{"kod":"12","nev":"Európa Könyvkiadó","szekhely":"Budapest"},
{"kod":"13","nev":"Magánkiadás","szekhely":""},
{"kod":"14","nev":"Széphalom Könyvműhely","szekhely":"Budapest"},
{"kod":"15","nev":"Árkádia Kiadó","szekhely":"Budapest"},
{"kod":"16","nev":"Fabula Kiadó","szekhely":"Budapest"},
{"kod":"17","nev":"Forum Könyvkiadó","szekhely":"Újvidék"},
{"kod":"18","nev":"Gulliver Könyvkiadó","szekhely":"Budapest"},
{"kod":"19","nev":"Natura Kiadó","szekhely":"Budapest"},
{"kod":"20","nev":"Gondolat Kiadó","szekhely":"Budapest"},
{"kod":"21","nev":"Bethlen Gábor Könyvkiadó","szekhely":"Budapest"},
{"kod":"22","nev":"Kriterion Könyvkiadó","szekhely":"Kolozsvár"},
{"kod":"23","nev":"Nesztor Kiadó","szekhely":"Budapest"},
{"kod":"24","nev":"Franklin Társulat","szekhely":"Budapest"},
{"kod":"25","nev":"Ifjúsági Lap- és Könyvkiadó Vállalat","szekhely":"Budapest"},
{"kod":"26","nev":"Minerva Kiadó","szekhely":"Budapest"},
{"kod":"27","nev":"Kossuth Könyvkiadó","szekhely":"Budapest"},
{"kod":"28","nev":"Zeneműkiadó Vállalat","szekhely":"Budapest"},
{"kod":"29","nev":"Corvina Kiadó","szekhely":"Budapest"},
{"kod":"30","nev":"Szak Kiadó","szekhely":"Bicske"},
{"kod":"31","nev":"Kiskapu Kft","szekhely":"Budapest"},
{"kod":"32","nev":"Openinfo Kiadó","szekhely":"Budapest"},
{"kod":"33","nev":"LSI Oktatóközpont","szekhely":"Budapest"},
{"kod":"34","nev":"Műszaki Könyvkiadó","szekhely":"Budapest"},
{"kod":"35","nev":"ComputerBooks Kiadó","szekhely":"Budapest"},
{"kod":"36","nev":"Szent Jeromos Kiadó","szekhely":"Budapest"},
{"kod":"37","nev":"Saxum Kiadó","szekhely":"Budapest"},
{"kod":"38","nev":"Zeneműkiadó Vállalat","szekhely":"Budapest"},
{"kod":"39","nev":"CMGK Kiadó","szekhely":"Budapest"},
{"kod":"40","nev":"Aranyhal Kiadó","szekhely":"Budapest"},
{"kod":"41","nev":"Tóth Könyvkereskedés és Kiadó","szekhely":"Debrecen"},
{"kod":"42","nev":"Maecenas Könyvkiadó","szekhely":"Budapest"},
{"kod":"43","nev":"Anno Kiadó","szekhely":"Budapest"}
]
