const konyvek=[
{"id":"1","szerzo":"Fajth Tibor","cim":"Svájc","ev":"1980","kiadokod":"1","oldal":"576","tema":"útikönyv"},
{"id":"2","szerzo":"Verzár István","cim":"Portugália","ev":"1984","kiadokod":"1","oldal":"519","tema":"útikönyv"},
{"id":"3","szerzo":"Polonyi Péter","cim":"Kína","ev":"1987","kiadokod":"1","oldal":"616","tema":"útikönyv"},
{"id":"4","szerzo":"Fehérdy Iván - Dukay Tóth Romola","cim":"Kanada","ev":"1985","kiadokod":"1","oldal":"549","tema":"útikönyv"},
{"id":"5","szerzo":"dr. Viczenik Dénes","cim":"Mexikó","ev":"1985","kiadokod":"1","oldal":"504","tema":"útikönyv"},
{"id":"6","szerzo":"Bács Gyula","cim":"Lengyelország","ev":"1976","kiadokod":"1","oldal":"618","tema":"útikönyv"},
{"id":"7","szerzo":"Szabó R. Jenő","cim":"Nagy-Britannia és Észak-Írország","ev":"1976","kiadokod":"1","oldal":"456","tema":"útikönyv"},
{"id":"8","szerzo":"Békési B. István","cim":"Törökország","ev":"1983","kiadokod":"1","oldal":"548","tema":"útikönyv"},
{"id":"9","szerzo":"Szentirmai József","cim":"Japán","ev":"1975","kiadokod":"1","oldal":"643","tema":"útikönyv"},
{"id":"10","szerzo":"Fajth Tibor","cim":"Itália","ev":"1969","kiadokod":"1","oldal":"639","tema":"útikönyv"},
{"id":"11","szerzo":"Pálfy József","cim":"Franciaország","ev":"1974","kiadokod":"1","oldal":"581","tema":"útikönyv"},
{"id":"12","szerzo":"Szíj Enikő","cim":"Finnország","ev":"1979","kiadokod":"1","oldal":"515","tema":"útikönyv"},
{"id":"13","szerzo":"Forgács András - Szabó Miklós","cim":"Görögország","ev":"1976","kiadokod":"1","oldal":"677","tema":"útikönyv"},
{"id":"14","szerzo":"Kis Csaba","cim":"Európai miniállamok","ev":"1985","kiadokod":"1","oldal":"404","tema":"útikönyv"},
{"id":"15","szerzo":"Szabó R. Jenő","cim":"Egyiptom","ev":"1979","kiadokod":"1","oldal":"622","tema":"útikönyv"},
{"id":"16","szerzo":"Lindner László","cim":"Dánia","ev":"1985","kiadokod":"1","oldal":"439","tema":"útikönyv"},
{"id":"17","szerzo":"Doromby Endre","cim":"Spanyolország","ev":"1976","kiadokod":"1","oldal":"629","tema":"útikönyv"},
{"id":"18","szerzo":"Kis Csaba","cim":"Amerikai Egyesült Államok","ev":"1982","kiadokod":"1","oldal":"744","tema":"útikönyv"},
{"id":"19","szerzo":"Balázs Dénes","cim":"Ausztrália, Új-Zéland, Óceánia","ev":"1981","kiadokod":"1","oldal":"832","tema":"útikönyv"},
{"id":"20","szerzo":"Pethő Tibor - Szombathy Viktor","cim":"Ausztria","ev":"1971","kiadokod":"1","oldal":"720","tema":"útikönyv"},
{"id":"21","szerzo":"Bács Gyula","cim":"Bulgária","ev":"1972","kiadokod":"1","oldal":"436","tema":"útikönyv"},
{"id":"22","szerzo":"Bede Béla - Lempert Márta","cim":"Brazília","ev":"1983","kiadokod":"1","oldal":"752","tema":"útikönyv"},
{"id":"23","szerzo":"Pálfy József","cim":"Benelux államok","ev":"1975","kiadokod":"1","oldal":"447","tema":"útikönyv"},
{"id":"24","szerzo":"Láng György","cim":"A Tamás-templom karnagya I-III.","ev":"1985","kiadokod":"2","oldal":"1059","tema":"zene"},
{"id":"25","szerzo":"Marafkó László","cim":"Irodalmi séták","ev":"1985","kiadokod":"3","oldal":"172","tema":"irodalomtörténet"},
{"id":"26","szerzo":"Márai Sándor","cim":"Füves könyv","ev":"1977","kiadokod":"4","oldal":"137","tema":"szépirodalom"},
{"id":"27","szerzo":"Márai Sándor","cim":"Napló 1958-1967","ev":"1999","kiadokod":"4","oldal":"368","tema":"szépirodalom"},
{"id":"28","szerzo":"Márai Sándor","cim":"Napló 1984-1989","ev":"1999","kiadokod":"4","oldal":"314","tema":"szépirodalom"},
{"id":"29","szerzo":"Márai Sándor","cim":"Egy polgár vallomásai I-II.","ev":"1990","kiadokod":"4","oldal":"392","tema":"szépirodalom"},
{"id":"30","szerzo":"Márai Sándor","cim":"Csutora","ev":"1991","kiadokod":"4","oldal":"126","tema":"szépirodalom"},
{"id":"31","szerzo":"Márai Sándor","cim":"Szindbád hazamegy","ev":"1992","kiadokod":"4","oldal":"126","tema":"szépirodalom"},
{"id":"32","szerzo":"Márai Sándor","cim":"A kassai polgárok","ev":"1990","kiadokod":"4","oldal":"191","tema":"szépirodalom"},
{"id":"33","szerzo":"Márai Sándor","cim":"Eszter hagyatéka","ev":"2001","kiadokod":"4","oldal":"294","tema":"szépirodalom"},
{"id":"34","szerzo":"Márai Sándor","cim":"A gyertyák csonkig égnek","ev":"1998","kiadokod":"4","oldal":"129","tema":"szépirodalom"},
{"id":"35","szerzo":"Krúdy Gyula","cim":"Álmoskönyv","ev":"1966","kiadokod":"5","oldal":"598","tema":"szépirodalom"},
{"id":"36","szerzo":"Krúdy Gyula","cim":"A tegnapok ködlovagjai","ev":"1961","kiadokod":"6","oldal":"676","tema":"szépirodalom"},
{"id":"37","szerzo":"Krúdy Gyula","cim":"A Tisza fia","ev":"1979","kiadokod":"7","oldal":"498","tema":"szépirodalom"},
{"id":"38","szerzo":"Krúdy Gyula","cim":"Szindbád","ev":"1973","kiadokod":"4","oldal":"865","tema":"szépirodalom"},
{"id":"39","szerzo":"Kosztolányi Dezső","cim":"Nyelv és lélek","ev":"1971","kiadokod":"6","oldal":"584","tema":"szépirodalom"},
{"id":"40","szerzo":"Kosztolányi Dezső","cim":"Pacsirta","ev":"1963","kiadokod":"6","oldal":"182","tema":"szépirodalom"},
{"id":"41","szerzo":"Kosztolányi Dezső","cim":"Nero, a véres költő","ev":"1957","kiadokod":"6","oldal":"286","tema":"szépirodalom"},
{"id":"42","szerzo":"Köntös-Szabó Zoltán","cim":"Fehér zászló Erdély felett","ev":"1992","kiadokod":"5","oldal":"412","tema":"szépirodalom"},
{"id":"43","szerzo":"Köntös-Szabó Zoltán","cim":"Tövissel kerített Éden","ev":"1994","kiadokod":"5","oldal":"420","tema":"szépirodalom"},
{"id":"44","szerzo":"Köntös-Szabó Zoltán","cim":"Köd lepte be a Szamost","ev":"1997","kiadokod":"8","oldal":"408","tema":"szépirodalom"},
{"id":"45","szerzo":"Köntös-Szabó Zoltán","cim":"Torda felől hírt hoz a szél","ev":"2002","kiadokod":"8","oldal":"492","tema":"szépirodalom"},
{"id":"46","szerzo":"Jókai Mór","cim":"A lőcsei fehér asszony","ev":"1982","kiadokod":"6","oldal":"516","tema":"szépirodalom"},
{"id":"47","szerzo":"Jókai Mór","cim":"Az arany ember","ev":"1981","kiadokod":"6","oldal":"584","tema":"szépirodalom"},
{"id":"48","szerzo":"Jókai Mór","cim":"Sárga rózsa","ev":"1979","kiadokod":"7","oldal":"96","tema":"szépirodalom"},
{"id":"49","szerzo":"Jókai Mór","cim":"Fekete gyémántok I-II.","ev":"1958","kiadokod":"6","oldal":"541","tema":"szépirodalom"},
{"id":"50","szerzo":"Jókai Mór","cim":"A huszti beteglátogatók","ev":"1982","kiadokod":"7","oldal":"366","tema":"szépirodalom"},
{"id":"51","szerzo":"Jókai Mór","cim":"Szegény gazdagok","ev":"1983","kiadokod":"6","oldal":"412","tema":"szépirodalom"},
{"id":"52","szerzo":"Jókai Mór","cim":"Az új földesúr","ev":"1991","kiadokod":"9","oldal":"326","tema":"szépirodalom"},
{"id":"53","szerzo":"Jókai Mór","cim":"És mégis mozog a Föld I-II.","ev":"1958","kiadokod":"6","oldal":"740","tema":"szépirodalom"},
{"id":"54","szerzo":"Jókai Mór","cim":"Akik kétszer halnak meg","ev":"1961","kiadokod":"6","oldal":"704","tema":"szépirodalom"},
{"id":"55","szerzo":"Jókai Mór","cim":"Egy magyar nábob","ev":"1977","kiadokod":"7","oldal":"504","tema":"szépirodalom"},
{"id":"56","szerzo":"Jókai Mór","cim":"Kárpáthy Zoltán","ev":"1979","kiadokod":"7","oldal":"452","tema":"szépirodalom"},
{"id":"57","szerzo":"Jókai Mór","cim":"A lélekidomár","ev":"1979","kiadokod":"10","oldal":"538","tema":"szépirodalom"},
{"id":"58","szerzo":"Jókai Mór","cim":"A kőszívű ember fiai","ev":"1996","kiadokod":"11","oldal":"534","tema":"szépirodalom"},
{"id":"59","szerzo":"James, Henry","cim":"Maisie tudja","ev":"1978","kiadokod":"12","oldal":"286","tema":"szépirodalom"},
{"id":"60","szerzo":"Jókai Anna","cim":"A reimsi angyal","ev":"1975","kiadokod":"6","oldal":"438","tema":"szépirodalom"},
{"id":"61","szerzo":"Jókai Anna","cim":"Szegény Sudár Anna","ev":"1989","kiadokod":"6","oldal":"438","tema":"szépirodalom"},
{"id":"62","szerzo":"Jókai Anna","cim":"Ima Magyarországért","ev":"2003","kiadokod":"13","oldal":"10","tema":"szépirodalom"},
{"id":"63","szerzo":"Jókai Anna","cim":"Ne féljetek","ev":"2005","kiadokod":"14","oldal":"343","tema":"szépirodalom"},
{"id":"64","szerzo":"Homérosz","cim":"Iliász. Odüszeia","ev":"1967","kiadokod":"4","oldal":"958","tema":"szépirodalom"},
{"id":"65","szerzo":"Hemingway, Ernest","cim":"Fiesta","ev":"1962","kiadokod":"12","oldal":"250","tema":"szépirodalom"},
{"id":"66","szerzo":"Hemingway, Ernest","cim":"Francis Macomber rövid boldogsága. A Kilimandzsáró hava","ev":"1970","kiadokod":"4","oldal":"73","tema":"szépirodalom"},
{"id":"67","szerzo":"Hemingway, Ernest","cim":"Akiért a harang szól","ev":"1983","kiadokod":"12","oldal":"526","tema":"szépirodalom"},
{"id":"68","szerzo":"Hemingway, Ernest","cim":"Veszélyes nyár","ev":"1988","kiadokod":"15","oldal":"272","tema":"szépirodalom"},
{"id":"69","szerzo":"Hemingway, Ernest","cim":"Vándorünnep","ev":"1968","kiadokod":"12","oldal":"236","tema":"szépirodalom"},
{"id":"70","szerzo":"Hemingway, Ernest","cim":"Elbeszélések","ev":"1992","kiadokod":"16","oldal":"288","tema":"szépirodalom"},
{"id":"71","szerzo":"Hemingway, Ernest","cim":"A folyón át, a fék közé","ev":"1966","kiadokod":"17","oldal":"318","tema":"szépirodalom"},
{"id":"72","szerzo":"Hemingway, Ernest","cim":"Búcsú a fegyverektől","ev":"1966","kiadokod":"12","oldal":"324","tema":"szépirodalom"},
{"id":"73","szerzo":"Durrell, Gerard","cim":"Vadállatok bolondja","ev":"1982","kiadokod":"7","oldal":"207","tema":"szórakoztató irodalom"},
{"id":"74","szerzo":"Durrell, Gerard","cim":"Szamártolvajok","ev":"1990","kiadokod":"18","oldal":"128","tema":"szórakoztató irodalom"},
{"id":"75","szerzo":"Durrell, Gerard","cim":"Vadak a vadonban","ev":"1988","kiadokod":"19","oldal":"173","tema":"szórakoztató irodalom"},
{"id":"76","szerzo":"Durrell, Gerard","cim":"Családom és egyéb állatfajták","ev":"1983","kiadokod":"12","oldal":"338","tema":"szórakoztató irodalom"},
{"id":"77","szerzo":"Durrell, Gerard","cim":"Istenek kertje","ev":"1986","kiadokod":"12","oldal":"262","tema":"szórakoztató irodalom"},
{"id":"78","szerzo":"Durrell, Gerard","cim":"Rokonom, Rosy","ev":"1983","kiadokod":"12","oldal":"268","tema":"szórakoztató irodalom"},
{"id":"79","szerzo":"Durrell, Gerard","cim":"Állatkert a poggyászomban","ev":"1985","kiadokod":"20","oldal":"213","tema":"szórakoztató irodalom"},
{"id":"80","szerzo":"Durrell, Jacquie","cim":"Állatok az ágyamban","ev":"1985","kiadokod":"12","oldal":"244","tema":"szórakoztató irodalom"},
{"id":"81","szerzo":"Hugo, Victor","cim":"A párizsi Notre Dame","ev":"1964","kiadokod":"12","oldal":"489","tema":"szépirodalom"},
{"id":"82","szerzo":"Hugo, Victor","cim":"A nyomorultak I-II.","ev":"1966","kiadokod":"12","oldal":"1360","tema":"szépirodalom"},
{"id":"83","szerzo":"Illyés Gyula","cim":"Ki a magyar","ev":"1982","kiadokod":"5","oldal":"66","tema":"szépirodalom"},
{"id":"84","szerzo":"Illyés Gyula","cim":"A Szentlélek karavánja","ev":"1987","kiadokod":"6","oldal":"348","tema":"szépirodalom"},
{"id":"85","szerzo":"Illyés Gyula","cim":"Puszták népe","ev":"1987","kiadokod":"6","oldal":"351","tema":"szépirodalom"},
{"id":"86","szerzo":"Illyés Gyula","cim":"Új látóhatár","ev":"1990","kiadokod":"21","oldal":"256","tema":"szépirodalom"},
{"id":"87","szerzo":"Illyés Gyula","cim":"Petőfi Sándor","ev":"1967","kiadokod":"6","oldal":"540","tema":"szépirodalom"},
{"id":"88","szerzo":"Illyés Gyula","cim":"Fáklyaláng","ev":"1958","kiadokod":"6","oldal":"103","tema":"szépirodalom"},
{"id":"89","szerzo":"Illyés Gyuláné","cim":"József Attila utolsó hónapjairól","ev":"1987","kiadokod":"6","oldal":"164","tema":"szépirodalom"},
{"id":"90","szerzo":"Esterházy Péter","cim":"Hrabal könyve","ev":"1990","kiadokod":"5","oldal":"185","tema":"szépirodalom"},
{"id":"91","szerzo":"Esterházy Péter","cim":"Harmonia caelestis","ev":"2000","kiadokod":"5","oldal":"714","tema":"szépirodalom"},
{"id":"92","szerzo":"Esterházy Péter","cim":"Javított kiadás","ev":"2002","kiadokod":"5","oldal":"281","tema":"szépirodalom"},
{"id":"93","szerzo":"Eco, Umberto","cim":"A rózsa neve","ev":"1988","kiadokod":"12","oldal":"664","tema":"szépirodalom"},
{"id":"94","szerzo":"Dumas, Alexandre","cim":"A jávai orvos","ev":"1966","kiadokod":"12","oldal":"318","tema":"szépirodalom"},
{"id":"95","szerzo":"Dumas, Alexandre","cim":"A három testőr","ev":"1989","kiadokod":"12","oldal":"660","tema":"szépirodalom"},
{"id":"96","szerzo":"Dumas, Alexandre","cim":"Monte Christo grófja I-III.","ev":"1979","kiadokod":"22","oldal":"1397","tema":"szépirodalom"},
{"id":"97","szerzo":"Brontë, Anne","cim":"Agnes Gray","ev":"1984","kiadokod":"12","oldal":"203","tema":"szépirodalom"},
{"id":"98","szerzo":"Brontë, Charlotte","cim":"Villette","ev":"1967","kiadokod":"12","oldal":"567","tema":"szépirodalom"},
{"id":"99","szerzo":"Brontë, Charlotte","cim":"Jane Eyre","ev":"1962","kiadokod":"12","oldal":"476","tema":"szépirodalom"},
{"id":"100","szerzo":"Brontë, Charlotte","cim":"A különös tanítvány","ev":"1989","kiadokod":"12","oldal":"216","tema":"szépirodalom"},
{"id":"101","szerzo":"Brontë, Emily","cim":"Üvöltő szelek","ev":"1967","kiadokod":"12","oldal":"327","tema":"szépirodalom"},
{"id":"102","szerzo":"Solohov, Mihail","cim":"Emberi sors","ev":"1964","kiadokod":"4","oldal":"75","tema":"szépirodalom"},
{"id":"103","szerzo":"Solohov, Mihail","cim":"Csendes Don I-IV.","ev":"1982","kiadokod":"12","oldal":"1807","tema":"szépirodalom"},
{"id":"104","szerzo":"Sienkiewicz, Henryk","cim":"Quo Vadis","ev":"1979","kiadokod":"12","oldal":"554","tema":"szépirodalom"},
{"id":"105","szerzo":"Sienkiewicz, Henryk","cim":"Kereszteslovagok I-II.","ev":"1968","kiadokod":"12","oldal":"967","tema":"szépirodalom"},
{"id":"106","szerzo":"Steinbeck, John","cim":"Édentől keletre I-II.","ev":"1979","kiadokod":"12","oldal":"773","tema":"szépirodalom"},
{"id":"107","szerzo":"Stendhal","cim":"Vanina vanini","ev":"1966","kiadokod":"12","oldal":"198","tema":"szépirodalom"},
{"id":"108","szerzo":"Stendhal","cim":"Vörös és fekete","ev":"1959","kiadokod":"12","oldal":"507","tema":"szépirodalom"},
{"id":"109","szerzo":"Stendhal","cim":"Vörös és fehér","ev":"1960","kiadokod":"12","oldal":"559","tema":"szépirodalom"},
{"id":"110","szerzo":"Shakespeare, William","cim":"Hamlet. Szentivánéji álom","ev":"1958","kiadokod":"6","oldal":"230","tema":"szépirodalom"},
{"id":"111","szerzo":"Shakespeare, William","cim":"Lear király","ev":"1957","kiadokod":"12","oldal":"184","tema":"szépirodalom"},
{"id":"112","szerzo":"Shakespeare, William","cim":"Sok hűhó semmiért","ev":"1960","kiadokod":"12","oldal":"107","tema":"szépirodalom"},
{"id":"113","szerzo":"Shakespeare, William","cim":"Tragédiák","ev":"1902","kiadokod":"24","oldal":"609","tema":"szépirodalom"},
{"id":"114","szerzo":"Semprum, Jorge","cim":"A nagy utazás","ev":"1986","kiadokod":"12","oldal":"214","tema":"szépirodalom"},
{"id":"115","szerzo":"Segal, Erich","cim":"Szerelmi történet","ev":"1982","kiadokod":"12","oldal":"136","tema":"szórakoztató irodalom"},
{"id":"116","szerzo":"Segal, Erich","cim":"Oliver története","ev":"1989","kiadokod":"12","oldal":"280","tema":"szórakoztató irodalom"},
{"id":"117","szerzo":"Sütő András","cim":"A szuzai menyegző","ev":"1981","kiadokod":"6","oldal":"135","tema":"szépirodalom"},
{"id":"118","szerzo":"Sütő András","cim":"Színművek","ev":"1989","kiadokod":"6","oldal":"282","tema":"szépirodalom"},
{"id":"119","szerzo":"Sütő András","cim":"Káin és Ábel. Anyám könnyű álmot ígér","ev":"1978","kiadokod":"5","oldal":"218","tema":"szépirodalom"},
{"id":"120","szerzo":"Sütő András","cim":"Omló egek alatt","ev":"1990","kiadokod":"6","oldal":"272","tema":"szépirodalom"},
{"id":"121","szerzo":"Sütő András","cim":"Síkaszói fenyőforgácsok","ev":"1987","kiadokod":"25","oldal":"182","tema":"szépirodalom"},
{"id":"122","szerzo":"Sütő András","cim":"Advent a Hargitán","ev":"1987","kiadokod":"6","oldal":"306","tema":"szépirodalom"},
{"id":"123","szerzo":"Sütő András","cim":"Az Idő markában","ev":"1984","kiadokod":"6","oldal":"436","tema":"szépirodalom"},
{"id":"124","szerzo":"Sütő András","cim":"A lőtt lábú madár nyomában","ev":"1988","kiadokod":"6","oldal":"384","tema":"szépirodalom"},
{"id":"125","szerzo":"Sütő András","cim":"Kék álhalál","ev":"1997","kiadokod":"10","oldal":"259","tema":"szépirodalom"},
{"id":"126","szerzo":"Sütő András","cim":"Anyám könnyű álmot ígér","ev":"1981","kiadokod":"6","oldal":"221","tema":"szépirodalom"},
{"id":"127","szerzo":"Probáld Ferenc - Szegedi Nándor","cim":"A világ fővárosai","ev":"1986","kiadokod":"27","oldal":"396","tema":"földrajz"},
{"id":"128","szerzo":"Darvas Gábor","cim":"Évezredek hangszerei","ev":"1961","kiadokod":"28","oldal":"232","tema":"zene"},
{"id":"129","szerzo":"Mittelstadt, Kuno","cim":"Vincent van Gogh","ev":"1976","kiadokod":"29","oldal":"65","tema":"képzőművészet"},
{"id":"130","szerzo":"Bergerhoff, Renate","cim":"Tiziano","ev":"1975","kiadokod":"29","oldal":"70","tema":"képzőművészet"},
{"id":"131","szerzo":"Füstös János","cim":"World Wide Web","ev":"1996","kiadokod":"30","oldal":"296","tema":"informatika"},
{"id":"132","szerzo":"Butzen, Fred - Hilton, Christopher","cim":"Linux hálózatok","ev":"1999","kiadokod":"31","oldal":"568","tema":"informatika"},
{"id":"133","szerzo":"Bartók Nagy János - Laufer Judit","cim":"UNIX felhasználói ismeretek","ev":"1995","kiadokod":"32","oldal":"388","tema":"informatika"},
{"id":"134","szerzo":"Szabó Bálint","cim":"Linux az otthoni PC-n","ev":"2000","kiadokod":"33","oldal":"266","tema":"informatika"},
{"id":"135","szerzo":"Kernighan, Brian - Ritchie, Dennis","cim":"A C programozási nyelv","ev":"1993","kiadokod":"34","oldal":"231","tema":"informatika"},
{"id":"136","szerzo":"Zsakó László","cim":"Programozási feladatok I-II.","ev":"1997","kiadokod":"27","oldal":"581","tema":"informatika"},
{"id":"137","szerzo":"Jamsa, Kris - Lalani, Suleiman - Weakley, Steve","cim":"A WEB programozása I-II.","ev":"1997","kiadokod":"27","oldal":"595","tema":"informatika"},
{"id":"138","szerzo":"Szelezsán János","cim":"Adatbázisok","ev":"1995","kiadokod":"33","oldal":"218","tema":"informatika"},
{"id":"139","szerzo":"Jakab Zsolt","cim":"Adobe Photoshop","ev":"1998","kiadokod":"35","oldal":"353","tema":"informatika"},
{"id":"140","szerzo":"Törőcsik Attila","cim":"Hangszerek kislexikona","ev":"2003","kiadokod":"37","oldal":"254","tema":"zene"},
{"id":"141","szerzo":"Brockhaus-Riemann","cim":"Zenei lexikon I-III.","ev":"1984","kiadokod":"38","oldal":"2023","tema":"zene"},
{"id":"142","szerzo":"Révész Dorrit","cim":"A zene könyve","ev":"1981","kiadokod":"38","oldal":"190","tema":"zene"},
{"id":"143","szerzo":"Szántó Péter","cim":"És ilyen a boksz?","ev":"1985","kiadokod":"9","oldal":"183","tema":"zene"},
{"id":"144","szerzo":"Gonda János","cim":"Jazz","ev":"1965","kiadokod":"38","oldal":"371","tema":"zene"},
{"id":"145","szerzo":"Molnár Imre - Molnár Gábor","cim":"Halhatatlan Beatles","ev":"2001","kiadokod":"39","oldal":"671","tema":"zene"},
{"id":"146","szerzo":"Simonyi Károly","cim":"A fizika kultúrtörténete","ev":"1986","kiadokod":"20","oldal":"539","tema":"fizika"},
{"id":"147","szerzo":"Öveges József","cim":"Kis fizika I-II.","ev":"1998","kiadokod":"40","oldal":"375","tema":"fizika"},
{"id":"148","szerzo":"Öveges József","cim":"Sugárözönben élünk","ev":"1995","kiadokod":"40","oldal":"239","tema":"fizika"},
{"id":"149","szerzo":"Öveges József","cim":"Klasszikus fizika","ev":"2000","kiadokod":"40","oldal":"245","tema":"fizika"},
{"id":"150","szerzo":"Veresné Horváth Éva","cim":"Miért piros a tilos?","ev":"1988","kiadokod":"34","oldal":"113","tema":"fizika"},
{"id":"151","szerzo":"Rókáné Kalydi Bea","cim":"300 kérdés és válasz a fizika köréből","ev":"2000","kiadokod":"41","oldal":"159","tema":"fizika"},
{"id":"152","szerzo":"Rókáné Kalydi Bea","cim":"150 kérdés és válasz a fizika köréből","ev":"1999","kiadokod":"41","oldal":"125","tema":"fizika"},
{"id":"153","szerzo":"Sas Elemér, dr.","cim":"Mindenki fizikája","ev":"2004","kiadokod":"40","oldal":"175","tema":"fizika"},
{"id":"154","szerzo":"Szalay Béla, dr.","cim":"Fizika","ev":"1982","kiadokod":"34","oldal":"922","tema":"fizika"},
{"id":"155","szerzo":"Holics László","cim":"Fizika I-II.","ev":"1986","kiadokod":"34","oldal":"1507","tema":"fizika"},
{"id":"156","szerzo":"Lennon - McCartney","cim":"Yesterday","ev":"1990","kiadokod":"42","oldal":"462","tema":"zene"},
{"id":"157","szerzo":"Larkin, Colin","cim":"Jazz-zenészek lexikona","ev":"1993","kiadokod":"27","oldal":"479","tema":"zene"},
{"id":"158","szerzo":"Menuhin, Yehudi - Davis, Curtis","cim":"Az ember zenéje","ev":"1981","kiadokod":"38","oldal":"319","tema":"zene"},
{"id":"159","szerzo":"Németh Amadé","cim":"Hangszerek és zenekarok kézikönyve","ev":"2000","kiadokod":"43","oldal":"271","tema":"zene"},
{"id":"160","szerzo":"Balassa Imre - Gál György Sándor","cim":"Operák könyve","ev":"1957","kiadokod":"28","oldal":"518","tema":"zene"},
{"id":"161","szerzo":"Gál György Sándor","cim":"Operák könyve","ev":"1961","kiadokod":"28","oldal":"423","tema":"zene"}
]
